env:
  es2021: true
  node: true
extends: eslint:recommended
plugins:
  - prettier
  - "@stylistic/js" # https://eslint.style/packages/js
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  "prettier/prettier": "error"
  "@stylistic/js/no-tabs": [error]
