name: Interval Updates

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */2 * * *"

jobs:
  main:
    name: Search & update job
    runs-on: ubuntu-latest

    env:
      OSU_API_KEY: ${{ secrets.OSU_API_KEY }}
      API_WAIT_TIME: ${{ vars.API_WAIT_TIME }}
      MAX_PAGE_DEPTH: ${{ vars.MAX_PAGE_DEPTH }}
      PAGE_WAIT_TIME: ${{ vars.PAGE_WAIT_TIME }}

    steps:
      - name: Copy this repo
        uses: actions/checkout@v4

      - name: Copy data branch into public dir
        uses: actions/checkout@v4
        with:
          ref: data
          path: ./public

      - name: Copy archived data to public dir
        run: cp -R ./.history/. ./public

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Use node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      # ---------------------------

      - name: Start lookup script
        run: node ./tools/lookup.js

      - name: Start fetch script
        run: node ./tools/fetch.js

      - name: Generate metadata
        run: node ./tools/generate/meta.js

      - name: Generate readme file
        run: node ./tools/generate/readme.js

      - name: Render markdown data
        uses: ZacJW/markdown-html-action@1.2.0
        with:
          input_files: '["./public/readme.md"]'
          output_files: '["./public/index.html"]'
          
      - name: Deploy data
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: data
          publish_dir: ./public
          commit_message: automated data update
          keep_files: true
